name: Push image to dockerhub
on:
  push:
    branches: [main]
jobs:
  list_all_api_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.list.outputs.versions }}
    container: grascm/android-tools-base:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: List all api versions
        id: list
        shell: bash
        run: echo "::set-output name=versions::$(./get_all_api_versions)"
  build_image:
    runs-on: ubuntu-latest
    needs: list_all_api_versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.list_all_api_versions.outputs.versions) }}
    steps:
      - name: Produce image tag
        id: tag
        run: |
          repo="${{ github.repository }}"
          tag="${repo/${{ github.repository_owner }}/grascm}:${{ matrix.version }}"
          echo $tag
          echo "::set-output name=res::$tag"
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2.3.0
        with:
          build-args: |
            API_VERSION=${{ matrix.version }}
          push: true
          tags: ${{ steps.tag.outputs.res }}
